In [3]:
import pandas as pd
df = pd.read_csv('orders.csv')
df.head()

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
0,1001,John Smith,Laptop,Electronics,1,1200.0,2024-06-01,Yes,USA
1,1002,Sarah Lee,Headphones,Electronics,2,150.0,2024-06-03,No,Canada
2,1003,Ali Khan,Office Chair,Furniture,1,300.0,2024-06-04,Yes,UAE
3,1004,Alice Wong,Desk Lamp,Furniture,3,45.0,2024-06-05,Yes,Singapore
4,1005,Carlos Mendez,Keyboard,Electronics,2,80.0,2024-06-06,No,Mexico

In [4]:
df.tail()

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
35,1036,Emma Thompson,Desk Lamp with USB,Furniture,1,68.0,2024-07-07,No,UK
36,1037,Carlos Santos,Wireless Earbuds,Electronics,1,125.0,2024-07-08,Yes,Portugal
37,1038,Leila Mansouri,Desk Pad,Furniture,1,28.0,2024-07-09,Yes,Iran
38,1039,Daniel Kim,Power Strip,Electronics,2,18.0,2024-07-10,No,South Korea
39,1040,Anna Ivanova,Desk Clock,Furniture,1,35.0,2024-07-11,Yes,Ukraine

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   OrderID       40 non-null     int64
 1   CustomerName  40 non-null     str
 2   Product       40 non-null     str
 3   Category      40 non-null     str
 4   Quantity      40 non-null     int64
 5   Price         40 non-null     float64
 6   OrderDate     40 non-null     str
 7   Shipped       40 non-null     str
 8   Country       40 non-null     str
dtypes: float64(1), int64(2), str(6)
memory usage: 2.9 KB

In [6]:
df.describe()

           OrderID    Quantity        Price
count    40.000000   40.000000    40.000000
mean   1020.500000    5.450000   106.457500
std      11.690452   15.903475   201.091854
min    1001.000000    1.000000     0.800000
25%    1010.750000    1.000000    18.000000
50%    1020.500000    1.000000    43.500000
75%    1030.250000    2.250000   112.500000
max    1040.000000  100.000000  1200.000000

In [7]:
df.columns

Index(['OrderID', 'CustomerName', 'Product', 'Category', 'Quantity', 'Price',
       'OrderDate', 'Shipped', 'Country'],
      dtype='str')

In [8]:
df.index

RangeIndex(start=0, stop=40, step=1)

In [9]:
df['Country']

0              USA
1           Canada
2              UAE
3        Singapore
4           Mexico
5              UAE
6               UK
7      South Korea
8            Italy
9            Japan
10          France
11           India
12       Australia
13           Spain
14           China
15           Egypt
16          Poland
17             USA
18           Japan
19    Saudi Arabia
20          Canada
21          Brazil
22         Germany
23        Pakistan
24          Sweden
25          France
26       Argentina
27          Russia
28     South Korea
29           Italy
30         Morocco
31         Germany
32        Colombia
33             USA
34           Japan
35              UK
36        Portugal
37            Iran
38     South Korea
39         Ukraine
Name: Country, dtype: str

In [10]:
df.iloc[5]

OrderID                 1006
CustomerName    Nora Ibrahim
Product             Notebook
Category          Stationery
Quantity                   5
Price                    5.0
OrderDate         2024-06-07
Shipped                  Yes
Country                  UAE
Name: 5, dtype: object

In [11]:
len(df["Country"])

40

In [12]:
set(df["Country"])

{'Argentina',
 'Australia',
 'Brazil',
 'Canada',
 'China',
 'Colombia',
 'Egypt',
 'France',
 'Germany',
 'India',
 'Iran',
 'Italy',
 'Japan',
 'Mexico',
 'Morocco',
 'Pakistan',
 'Poland',
 'Portugal',
 'Russia',
 'Saudi Arabia',
 'Singapore',
 'South Korea',
 'Spain',
 'Sweden',
 'UAE',
 'UK',
 'USA',
 'Ukraine'}

In [16]:
df.iloc[1] # Index Location

OrderID                1002
CustomerName      Sarah Lee
Product          Headphones
Category        Electronics
Quantity                  2
Price                 150.0
OrderDate        2024-06-03
Shipped                  No
Country              Canada
Name: 1, dtype: object

In [15]:
df[["Country", "Product"]]

         Country                Product
0            USA                 Laptop
1         Canada             Headphones
2            UAE           Office Chair
3      Singapore              Desk Lamp
4         Mexico               Keyboard
5            UAE               Notebook
6             UK          Standing Desk
7    South Korea                Monitor
8          Italy                    Pen
9          Japan                  Mouse
10        France                 Webcam
11         India           File Cabinet
12     Australia                Stapler
13         Spain              USB Drive
14         China              Bookshelf
15         Egypt          Printer Paper
16        Poland         Wireless Mouse
17           USA         Desk Organizer
18         Japan             Calculator
19  Saudi Arabia             Whiteboard
20        Canada           Highlighters
21        Brazil      Bluetooth Speaker
22       Germany           Office Plant
23      Pakistan           Sticky Notes
24        Sweden           Tablet Stand
25        France         Paper Shredder
26     Argentina         Desk Chair Mat
27        Russia           Binder Clips
28   South Korea      Wireless Keyboard
29         Italy          Desk Calendar
30       Morocco                USB Hub
31       Germany       Document Scanner
32      Colombia  Desk Drawer Organizer
33           USA            Index Cards
34         Japan          Monitor Stand
35            UK     Desk Lamp with USB
36      Portugal       Wireless Earbuds
37          Iran               Desk Pad
38   South Korea            Power Strip
39       Ukraine             Desk Clock

In [23]:
df.iloc[10, 2]

'Webcam'

In [25]:
df.iloc[1]['Country']

'Canada'

In [28]:
df[df['Category'] == 'Furniture']

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
2,1003,Ali Khan,Office Chair,Furniture,1,300.0,2024-06-04,Yes,UAE
3,1004,Alice Wong,Desk Lamp,Furniture,3,45.0,2024-06-05,Yes,Singapore
6,1007,Emily Davis,Standing Desk,Furniture,1,450.0,2024-06-08,Yes,UK
11,1012,Raj Patel,File Cabinet,Furniture,2,180.0,2024-06-13,No,India
14,1015,Lisa Chen,Bookshelf,Furniture,1,280.0,2024-06-16,No,China
17,1018,Michael Brown,Desk Organizer,Furniture,1,65.0,2024-06-19,No,USA
19,1020,Fatima Al-Zahra,Whiteboard,Furniture,1,120.0,2024-06-21,Yes,Saudi Arabia
22,1023,Oliver Schmidt,Office Plant,Furniture,2,35.0,2024-06-24,Yes,Germany
26,1027,Miguel Torres,Desk Chair Mat,Furniture,1,22.0,2024-06-28,No,Argentina
29,1030,Giuseppe Romano,Desk Calendar,Furniture,1,18.0,2024-07-01,No,Italy
32,1033,Sofia Rodriguez,Desk Drawer Organizer,Furniture,1,42.0,2024-07-04,No,Colombia
35,1036,Emma Thompson,Desk Lamp with USB,Furniture,1,68.0,2024-07-07,No,UK
37,1038,Leila Mansouri,Desk Pad,Furniture,1,28.0,2024-07-09,Yes,Iran
39,1040,Anna Ivanova,Desk Clock,Furniture,1,35.0,2024-07-11,Yes,Ukraine

In [ ]:
# Multiple conditions - AND
df[(df['Category'] == 'Furniture') & (df['Price'] > 100)]

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
2,1003,Ali Khan,Office Chair,Furniture,1,300.0,2024-06-04,Yes,UAE
6,1007,Emily Davis,Standing Desk,Furniture,1,450.0,2024-06-08,Yes,UK
11,1012,Raj Patel,File Cabinet,Furniture,2,180.0,2024-06-13,No,India
14,1015,Lisa Chen,Bookshelf,Furniture,1,280.0,2024-06-16,No,China
19,1020,Fatima Al-Zahra,Whiteboard,Furniture,1,120.0,2024-06-21,Yes,Saudi Arabia

In [32]:
# Multiple conditions - OR
df[(df['Category'] == 'Clothing') | (df['Price'] > 100)]

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
0,1001,John Smith,Laptop,Electronics,1,1200.0,2024-06-01,Yes,USA
1,1002,Sarah Lee,Headphones,Electronics,2,150.0,2024-06-03,No,Canada
2,1003,Ali Khan,Office Chair,Furniture,1,300.0,2024-06-04,Yes,UAE
6,1007,Emily Davis,Standing Desk,Furniture,1,450.0,2024-06-08,Yes,UK
7,1008,James Park,Monitor,Electronics,2,220.0,2024-06-09,No,South Korea
11,1012,Raj Patel,File Cabinet,Furniture,2,180.0,2024-06-13,No,India
14,1015,Lisa Chen,Bookshelf,Furniture,1,280.0,2024-06-16,No,China
19,1020,Fatima Al-Zahra,Whiteboard,Furniture,1,120.0,2024-06-21,Yes,Saudi Arabia
28,1029,Seo-yeon Kim,Wireless Keyboard,Electronics,1,110.0,2024-06-30,Yes,South Korea
31,1032,Thomas Müller,Document Scanner,Electronics,1,140.0,2024-07-03,Yes,Germany
36,1037,Carlos Santos,Wireless Earbuds,Electronics,1,125.0,2024-07-08,Yes,Portugal

In [35]:
# Multiple conditions - Comparison operators
df[df['Quantity'] > 10] # uther comparison operators: <, <=, >, >=, !=

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
15,1016,Ahmed Hassan,Printer Paper,Stationery,20,8.0,2024-06-17,Yes,Egypt
23,1024,Zara Ahmed,Sticky Notes,Stationery,15,4.0,2024-06-25,No,Pakistan
27,1028,Nina Petrov,Binder Clips,Stationery,12,2.5,2024-06-29,Yes,Russia
33,1034,Alex Johnson,Index Cards,Stationery,100,0.8,2024-07-05,Yes,USA

In [43]:
# String methods
df[df['CustomerName'].str.startswith('A')] # other string methods: endswith(), contains(), len(), lower(), upper()

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
2,1003,Ali Khan,Office Chair,Furniture,1,300.0,2024-06-04,Yes,UAE
3,1004,Alice Wong,Desk Lamp,Furniture,3,45.0,2024-06-05,Yes,Singapore
15,1016,Ahmed Hassan,Printer Paper,Stationery,20,8.0,2024-06-17,Yes,Egypt
16,1017,Anna Kowalski,Wireless Mouse,Electronics,2,45.0,2024-06-18,Yes,Poland
30,1031,Amira Hassan,USB Hub,Electronics,1,32.0,2024-07-02,Yes,Morocco
33,1034,Alex Johnson,Index Cards,Stationery,100,0.8,2024-07-05,Yes,USA
39,1040,Anna Ivanova,Desk Clock,Furniture,1,35.0,2024-07-11,Yes,Ukraine

In [ ]:
# boolean/conditional/predicate methods.
df[df['Category'].isin(['Furniture', 'Clothing'])] # other methods: notin(), between(), isnull(), notnull()

In [47]:
# ~ Negation operator
df[~df['Country'].isin(['United States', 'Canada', 'Mexico'])] # other boolean operators: &, |, ^, ==, !=, >, <, >=, <=

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
0,1001,John Smith,Laptop,Electronics,1,1200.0,2024-06-01,Yes,USA
2,1003,Ali Khan,Office Chair,Furniture,1,300.0,2024-06-04,Yes,UAE
3,1004,Alice Wong,Desk Lamp,Furniture,3,45.0,2024-06-05,Yes,Singapore
5,1006,Nora Ibrahim,Notebook,Stationery,5,5.0,2024-06-07,Yes,UAE
6,1007,Emily Davis,Standing Desk,Furniture,1,450.0,2024-06-08,Yes,UK
7,1008,James Park,Monitor,Electronics,2,220.0,2024-06-09,No,South Korea
8,1009,Maria Rossi,Pen,Stationery,10,1.5,2024-06-10,Yes,Italy
9,1010,Takeshi Nakamura,Mouse,Electronics,1,35.0,2024-06-11,Yes,Japan
10,1011,Sophie Martin,Webcam,Electronics,1,85.0,2024-06-12,Yes,France
11,1012,Raj Patel,File Cabinet,Furniture,2,180.0,2024-06-13,No,India
12,1013,Emma Wilson,Stapler,Stationery,3,12.0,2024-06-14,Yes,Australia
13,1014,Diego Rodriguez,USB Drive,Electronics,5,25.0,2024-06-15,Yes,Spain
14,1015,Lisa Chen,Bookshelf,Furniture,1,280.0,2024-06-16,No,China
15,1016,Ahmed Hassan,Printer Paper,Stationery,20,8.0,2024-06-17,Yes,Egypt
16,1017,Anna Kowalski,Wireless Mouse,Electronics,2,45.0,2024-06-18,Yes,Poland
17,1018,Michael Brown,Desk Organizer,Furniture,1,65.0,2024-06-19,No,USA
18,1019,Yuki Tanaka,Calculator,Electronics,1,15.0,2024-06-20,Yes,Japan
19,1020,Fatima Al-Zahra,Whiteboard,Furniture,1,120.0,2024-06-21,Yes,Saudi Arabia
21,1022,Isabella Silva,Bluetooth Speaker,Electronics,1,95.0,2024-06-23,Yes,Brazil
22,1023,Oliver Schmidt,Office Plant,Furniture,2,35.0,2024-06-24,Yes,Germany
23,1024,Zara Ahmed,Sticky Notes,Stationery,15,4.0,2024-06-25,No,Pakistan
24,1025,Lucas Anderson,Tablet Stand,Electronics,1,28.0,2024-06-26,Yes,Sweden
25,1026,Chloe Dubois,Paper Shredder,Electronics,1,75.0,2024-06-27,Yes,France
26,1027,Miguel Torres,Desk Chair Mat,Furniture,1,22.0,2024-06-28,No,Argentina
27,1028,Nina Petrov,Binder Clips,Stationery,12,2.5,2024-06-29,Yes,Russia
28,1029,Seo-yeon Kim,Wireless Keyboard,Electronics,1,110.0,2024-06-30,Yes,South Korea
29,1030,Giuseppe Romano,Desk Calendar,Furniture,1,18.0,2024-07-01,No,Italy
30,1031,Amira Hassan,USB Hub,Electronics,1,32.0,2024-07-02,Yes,Morocco
31,1032,Thomas Müller,Document Scanner,Electronics,1,140.0,2024-07-03,Yes,Germany
32,1033,Sofia Rodriguez,Desk Drawer Organizer,Furniture,1,42.0,2024-07-04,No,Colombia
33,1034,Alex Johnson,Index Cards,Stationery,100,0.8,2024-07-05,Yes,USA
34,1035,Yuki Yamamoto,Monitor Stand,Electronics,1,55.0,2024-07-06,Yes,Japan
35,1036,Emma Thompson,Desk Lamp with USB,Furniture,1,68.0,2024-07-07,No,UK
36,1037,Carlos Santos,Wireless Earbuds,Electronics,1,125.0,2024-07-08,Yes,Portugal
37,1038,Leila Mansouri,Desk Pad,Furniture,1,28.0,2024-07-09,Yes,Iran
38,1039,Daniel Kim,Power Strip,Electronics,2,18.0,2024-07-10,No,South Korea
39,1040,Anna Ivanova,Desk Clock,Furniture,1,35.0,2024-07-11,Yes,Ukraine

In [53]:
# Updating values: increase price by 10% for furniture items
df.loc[df['Category'] == 'Furniture', 'Price'] = df['Price'] * 1.1

In [52]:
# update product for Anna Ivanova to Office Chair
df.loc[df['CustomerName'] == 'Anna Ivanova', 'Product'] = 'Office Chair'

In [ ]:
# Display the updated row for Anna Ivanova
df.loc[df['CustomerName'] == 'Anna Ivanova']

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
39,1040,Anna Ivanova,Office Chair,Furniture,1,38.5,2024-07-11,Yes,Ukraine

In [57]:
# Convert country names to uppercase for all rows
df['Country'] = df['Country'].str.upper()

In [58]:
# Delete a row by index
df = df.drop(39)

In [59]:
# Display the final DataFrame 
df.tail()

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
34,1035,Yuki Yamamoto,Monitor Stand,Electronics,1,55.00,2024-07-06,Yes,JAPAN
35,1036,Emma Thompson,Desk Lamp with USB,Furniture,1,82.28,2024-07-07,No,UK
36,1037,Carlos Santos,Wireless Earbuds,Electronics,1,125.00,2024-07-08,Yes,PORTUGAL
37,1038,Leila Mansouri,Desk Pad,Furniture,1,33.88,2024-07-09,Yes,IRAN
38,1039,Daniel Kim,Power Strip,Electronics,2,18.00,2024-07-10,No,SOUTH KOREA

In [ ]:
df["Country"].value_counts() # other methods: unique(), nunique(), count(), mean(), median(), mode(), std(), var(), min(), max()

Country
USA             3
SOUTH KOREA     3
JAPAN           3
CANADA          2
UAE             2
UK              2
ITALY           2
FRANCE          2
GERMANY         2
SINGAPORE       1
MEXICO          1
INDIA           1
AUSTRALIA       1
SPAIN           1
CHINA           1
EGYPT           1
POLAND          1
SAUDI ARABIA    1
BRAZIL          1
PAKISTAN        1
SWEDEN          1
ARGENTINA       1
RUSSIA          1
MOROCCO         1
COLOMBIA        1
PORTUGAL        1
IRAN            1
Name: count, dtype: int64

In [68]:
df['Price'].mean()

np.float64(117.19051282051282)

## aggregation/statistical methods in pandas. They work on a numeric Series, not on a string column
* `mean()`   → the average value.
* `median()`  → the middle value after sorting. For number values only.
* `mode()`  → the most frequent value. Works for strings too.
* `std()`  → standard deviation.  For number values only.
* `var()`  → variance.  For number values only.
* `min()`  → the minimum value.
* `max()`  → the maximum value.

In [73]:
# total sales by country
df.groupby(['Country'])['Price'].sum() # calculates the total sales by country

Country
ARGENTINA         26.62
AUSTRALIA         12.00
BRAZIL            95.00
CANADA           153.50
CHINA            338.80
COLOMBIA          50.82
EGYPT              8.00
FRANCE           160.00
GERMANY          182.35
INDIA            217.80
IRAN              33.88
ITALY             23.28
JAPAN            105.00
MEXICO            80.00
MOROCCO           32.00
PAKISTAN           4.00
POLAND            45.00
PORTUGAL         125.00
RUSSIA             2.50
SAUDI ARABIA     145.20
SINGAPORE         54.45
SOUTH KOREA      348.00
SPAIN             25.00
SWEDEN            28.00
UAE              368.00
UK               626.78
USA             1279.45
Name: Price, dtype: float64

In [ ]:
df.sort_values('Price', ascending=False)

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
0,1001,John Smith,Laptop,Electronics,1,1200.00,2024-06-01,Yes,USA
6,1007,Emily Davis,Standing Desk,Furniture,1,544.50,2024-06-08,Yes,UK
2,1003,Ali Khan,Office Chair,Furniture,1,363.00,2024-06-04,Yes,UAE
14,1015,Lisa Chen,Bookshelf,Furniture,1,338.80,2024-06-16,No,CHINA
7,1008,James Park,Monitor,Electronics,2,220.00,2024-06-09,No,SOUTH KOREA
11,1012,Raj Patel,File Cabinet,Furniture,2,217.80,2024-06-13,No,INDIA
1,1002,Sarah Lee,Headphones,Electronics,2,150.00,2024-06-03,No,CANADA
19,1020,Fatima Al-Zahra,Whiteboard,Furniture,1,145.20,2024-06-21,Yes,SAUDI ARABIA
31,1032,Thomas Müller,Document Scanner,Electronics,1,140.00,2024-07-03,Yes,GERMANY
36,1037,Carlos Santos,Wireless Earbuds,Electronics,1,125.00,2024-07-08,Yes,PORTUGAL
28,1029,Seo-yeon Kim,Wireless Keyboard,Electronics,1,110.00,2024-06-30,Yes,SOUTH KOREA
21,1022,Isabella Silva,Bluetooth Speaker,Electronics,1,95.00,2024-06-23,Yes,BRAZIL
10,1011,Sophie Martin,Webcam,Electronics,1,85.00,2024-06-12,Yes,FRANCE
35,1036,Emma Thompson,Desk Lamp with USB,Furniture,1,82.28,2024-07-07,No,UK
4,1005,Carlos Mendez,Keyboard,Electronics,2,80.00,2024-06-06,No,MEXICO
17,1018,Michael Brown,Desk Organizer,Furniture,1,78.65,2024-06-19,No,USA
25,1026,Chloe Dubois,Paper Shredder,Electronics,1,75.00,2024-06-27,Yes,FRANCE
34,1035,Yuki Yamamoto,Monitor Stand,Electronics,1,55.00,2024-07-06,Yes,JAPAN
3,1004,Alice Wong,Desk Lamp,Furniture,3,54.45,2024-06-05,Yes,SINGAPORE
32,1033,Sofia Rodriguez,Desk Drawer Organizer,Furniture,1,50.82,2024-07-04,No,COLOMBIA
16,1017,Anna Kowalski,Wireless Mouse,Electronics,2,45.00,2024-06-18,Yes,POLAND
22,1023,Oliver Schmidt,Office Plant,Furniture,2,42.35,2024-06-24,Yes,GERMANY
9,1010,Takeshi Nakamura,Mouse,Electronics,1,35.00,2024-06-11,Yes,JAPAN
37,1038,Leila Mansouri,Desk Pad,Furniture,1,33.88,2024-07-09,Yes,IRAN
30,1031,Amira Hassan,USB Hub,Electronics,1,32.00,2024-07-02,Yes,MOROCCO
24,1025,Lucas Anderson,Tablet Stand,Electronics,1,28.00,2024-06-26,Yes,SWEDEN
26,1027,Miguel Torres,Desk Chair Mat,Furniture,1,26.62,2024-06-28,No,ARGENTINA
13,1014,Diego Rodriguez,USB Drive,Electronics,5,25.00,2024-06-15,Yes,SPAIN
29,1030,Giuseppe Romano,Desk Calendar,Furniture,1,21.78,2024-07-01,No,ITALY
38,1039,Daniel Kim,Power Strip,Electronics,2,18.00,2024-07-10,No,SOUTH KOREA
18,1019,Yuki Tanaka,Calculator,Electronics,1,15.00,2024-06-20,Yes,JAPAN
12,1013,Emma Wilson,Stapler,Stationery,3,12.00,2024-06-14,Yes,AUSTRALIA
15,1016,Ahmed Hassan,Printer Paper,Stationery,20,8.00,2024-06-17,Yes,EGYPT
5,1006,Nora Ibrahim,Notebook,Stationery,5,5.00,2024-06-07,Yes,UAE
23,1024,Zara Ahmed,Sticky Notes,Stationery,15,4.00,2024-06-25,No,PAKISTAN
20,1021,David Thompson,Highlighters,Stationery,8,3.50,2024-06-22,No,CANADA
27,1028,Nina Petrov,Binder Clips,Stationery,12,2.50,2024-06-29,Yes,RUSSIA
8,1009,Maria Rossi,Pen,Stationery,10,1.50,2024-06-10,Yes,ITALY
33,1034,Alex Johnson,Index Cards,Stationery,100,0.80,2024-07-05,Yes,USA